name: "air-quality"

services:
  mongo:
    image: mongo:8.0
    container_name: mongodb
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes: 
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/mongodb
    
